### ISSUE TITLE
Base64 can not decode values including an uppercase A

### ISSUE THREAD

**Issue by Sebaestschjin** [Benjamin-Dobell/ge_tts#14]
When using the `Base64.decode` method, it fails when the encoded string contains an uppsercase A letter (e.g. minimal example I used `biA=`).  The error is

`attempt to perform arithmetic on a nil value`

on the line:

 `local v = map[a] * 0x40000 + map[b] * 0x1000 + map[c] * 0x40 + map[d]`

The reason is, the first index of the default encoding is zero. The default decoding map is build by using `TableUtils.invert` on the encoding map. This then uses `TableUtils.iterate` to iterate over the table. Since its not a fixed length array it uses `ipairs` to iterate which starts at index 1. So the default decoding map doesn't include a value for the letter A.

**Comment by Benjamin-Dobell** [comment]
Sorry, https://github.com/Benjamin-Dobell/ge_tts/commit/8e3f9fd087671bb3a2638d6a8710216a385d4807 was a lot more _breaking_ than I intended!
