### ISSUE TITLE
DropZone can't pickup from a deck

### ISSUE THREAD

**Issue by Zehir** [Benjamin-Dobell/ge_tts#6]
If you have a Deck inside a dropZone you can't pick up a card because of this:
https://github.com/Benjamin-Dobell/ge_tts/blob/3b792a7b67a677e7164548e15eeba4721e034ce6/Zone.ttslua#L395-L397
The newly spawned card that you hold is forced to be dropped so you can't pick it. A quick fix is to add `and object.held_by_color == nil` in the if but if you `cut` or `split` the deck he will be merged and sometime this is not the correct guid of the deck in the `occupying` table.

**Comment by Benjamin-Dobell** [comment]
> cut or split the deck he will be merged and sometime this is not the correct guid of the deck in the occupying table.

Admittedly, it's not really designed to handle cut or split, as it's not really obvious what should happen. By calling drop on the zone, this does at least give you a chance to try handle the dropped object yourself.

_However_, the changing GUID thing a bit of problem. You're quite welcome to open a separate issue about cut/split to keep track of the undesirable behaviour.
