### ISSUE TITLE
Object not counted when going back to `pick_up_position`

### ISSUE THREAD

**Issue by Zehir** [Benjamin-Dobell/ge_tts#7]
A new feature in 12.4 introduce a way to move a object where he was picked up when you press escape.
The `occupying` table is not correctly updated when you use this new feature after pick it a object from a zone.

**Comment by Benjamin-Dobell** [comment]
The fix for this is visibly glitchy if the object has been rotated from the the drop zone's rotation (when auto rotation is enabled).

I suspect I'll need additional TTS APIs to resolve this, but will look into it further later on.

**Comment by Benjamin-Dobell** [comment]
Actually, the current "fix" is a bit overzealous. I'll do a better job once I've got some more free time 😉

**Comment by Benjamin-Dobell** [comment]
Figured I may as well just quickly get it done. It's not exactly optimal performance-wise, but does the job.

**EDIT**: Rotation glitches still persists.
